### ISSUE TITLE
Error: The server does not support SSL connections

### ISSUE THREAD

**Issue by alxgrk** [dbos-inc/ttdbg-extension#38]
Hey,

I got an error while trying to debug a workflow:
```
$ npx dbos-sdk debug -x postgresql://localhost:2345 -u 95f62e02-e9a1-4f65-b061-2e96cfd85838
Debugger attached.
Debugger attached.
2024-07-02 14:39:00 [info]: Running in debug mode! 
2024-07-02 14:39:00 [info]: Debugging mode proxy: localhost:2345 
2024-07-02 14:39:00 [info]: Workflow executor initialized 
2024-07-02 14:39:00 [error]: Debug mode error: The server does not support SSL connections 
    at GlobalLogger.error (.../node_modules/@dbos-inc/dbos-sdk/dist/src/telemetry/logs.js:63:65)
    at debugWorkflow (.../node_modules/@dbos-inc/dbos-sdk/dist/src/dbos-runtime/debug.js:24:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (.../node_modules/@dbos-inc/dbos-sdk/dist/src/dbos-runtime/cli.js:40:5)
```

Not really sure, how SSL comes into play here. Any idea?

**Comment by devhawk** [comment]
Thanks for filing the issue @alxgrk! I'd rather have a spuriously opened issue that we can close easily than losing the context on a problem. If this is still an issue, let me know!

**Comment by alxgrk** [comment]
@devhawk I guess a hint why `debug` considers the yaml's DB URL in the docs could be an option - or, if it doesn't need that config, it could skip reading it. Apart from that, I would also be fine with closing this issue.
